export const LOGIN = {
    REQUEST: 'LOGIN_REQUEST',
    SUCCESS: 'LOGIN_SUCCESS',
}

export const REGISTER = {
    REQUEST: 'REGISTER_REQUEST',
    SUCCESS: 'REGISTER_SUCCESS',
}

export const GET_KANBAN = {
    REQUEST: 'GET_KANBAN_REQUEST',
    SUCCESS: 'GET_KANBAN_SUCCESS'
}

export const UPDATE_KANBAN = {
    REQUEST: 'UPDATE_KANBAN_REQUEST',
    SUCCESS: 'UPDATE_KANBAN_SUCCESS'
}

export const CREATE_KANBAN = {
    REQUEST: 'CREATE_KANBAN_REQUEST',
    SUCCESS: 'CREATE_KANBAN_SUCCESS'
}